import Head from 'next/head';
import { useState } from 'react';


export default function Home() {
  const [message, setmessage] = useState("");
  // https://icon.horse/icon/google.com for generating favicons
  // https://api.postalpincode.in/pincode/503111 for get postal details
  return (
    <div className="">
      <Head>
        <title>QR CODE GENERATOR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section class="text-gray-600 body-font relative">
          <div class="container px-5 py-24 mx-auto">
            <div className="title text-center text-blue-500">
              <h1 className='text-3xl'>Generate QR Code</h1>
            </div>
            <div class="lg:w-1/2 md:w-2/3 mx-auto">
              <div class="flex flex-wrap -m-2">

                <div class="p-2 w-full">
                  <div class="relative">
                    <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
                    <textarea value={message} onChange={(e) => setmessage(e.target.value)} id="message" name="message" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
                  </div>
                </div>
                <div class="p-2 w-full">
                  <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Generate</button>
                </div>
                <div className="qr">
                  <h1>{message.toString}</h1>
                </div>
                <div className=" mx-auto justify-center">
                  <img src={"https://api.qrserver.com/v1/create-qr-code/?size=450x450&data=" + message} alt="" />
                  {/* <img src={"https://qr-code-generator-cqsj.onrender.com/qr?url=" + message} alt="" /> */}
                </div>

              </div>
            </div>
          </div>
        </section>
      </main>

    </div>


  )
}
